Fix GCC 5.3.0 compilation (missing pthread)
ldd is failing to compile on SLC6 with GCC 5.3.0 due to missing pthread
on link command. In all cases we have undefined reference to
`pthread_create` symbol.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>